version: "3"
services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always

    ports:
      # <Port exposed> : < MySQL Port running inside container>
      # default is:
      #- '3306:3306'
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - .docker/mysql:/var/lib/mysql
    env_file:
      - .env
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --requirepass "12345"
